export const SAUDI_UNIVERSITIES = [
  "King Saud University",
  "King Abdulaziz University",
  "KFUPM",
  "Princess Nourah University",
  "Imam University",
  "Umm Al-Qura University",
  "Qassim University",
  "Taibah University",
  "Jouf University",
  "Najran University",
  "Jazan University",
  "Northern Border University",
  "King Faisal University",
  "Taif University",
  "Prince Sultan University",
  "Alfaisal University",
  "Effat University",
  "Dar Al-Hekma University",
  "King Khalid University",
  "Shaqra University",
  "Majmaah University",
  "University of Tabuk",
  "University of Hail",
  "Saudi Electronic University",
  "University of Bisha",
  "University of Jeddah",
  "Prince Sattam bin Abdulaziz University",
  "Prince Mohammad bin Fahd University",
];

export const COMMON_MAJORS = [
  "Computer Science",
  "Cybersecurity",
  "Information Technology",
  "Software Engineering",
  "Data Science",
  "Artificial Intelligence",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Industrial Engineering",
  "Business Administration",
  "Finance",
  "Accounting",
  "Marketing",
  "Human Resources",
  "Medicine",
  "Nursing",
  "Law",
  "Architecture",
  "Interior Design",
  "Graphic Design",
  "Media & Communication",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
];
